Fix spring stiffness for BarReleases
BHoM/ETABS_Toolkit pull request #394
Opened 2021-12-22 14:36 UTC by IsakNaslundBh

### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #393 

 

Makes sure the spring stiffness is picked up by changing the check if a DOF is released from checking if identical to free to instead check if it is not fixed.

 ### Test files

 ### Changelog

 ### Additional comments

2021-12-29 22:42 UTC, JosefTaylor requested changes
Needs similar change in ToBHoM in order to catch springs - see changes in SAP2000
Push works properly.

2022-01-03 15:41 UTC, IsakNaslundBh commented
thanks @JosefTaylor .

Have fixed now!

2022-01-03 21:51 UTC, JosefTaylor requested changes
axes are switched between pulling and pushing

2022-01-03 21:51 UTC, JosefTaylor commented on Etabs_Adapter/CRUD/Read/Bar.cs
> +
Push uses XZY, pull uses XYZ- I am not sure which one is right! I think it is XZY.

2022-01-04 10:30 UTC, IsakNaslundBh commented
> axes are switched between pulling and pushing: Push uses XZY, pull uses XYZ- I am not sure which one is right! I think it is XZY.

You are right 🤦‍♂️ . Have fixed now, thanks for spotting.

Also added another section of the script to verify that the order is correct by looking at reactions, and as you stated, XZY looks to be correct. Really confusing with Etabs Left-hand rule with switched orientations between 1 and 2 compared to BHoM (and what I have seen in most other packages).

Anyhow, code updated and added a small method over the quite long statement of ?s and :s as I found that a bit hard to read if we look at this again :)

2022-01-05 14:48 UTC, JosefTaylor approved these changes
Works great!

2022-01-05 15:12 UTC, JosefTaylor commented
I have this transform matrix in SAP2000; is there a way we could use it to create releases?
`        public static TransformMatrix barLocalAxisToBHoM = new TransformMatrix()
        {
            Matrix = new double[4, 4]
            {
                { 1,  0,  0, 0 },
                { 0,  0, -1, 0 },
                { 0,  1,  0, 0 },
                { 0,  0,  0, 1 }
            }
        };`

2022-01-11 14:05 UTC, IsakNaslundBh commented
@BHoMBot check required

2022-01-11 14:06 UTC, IsakNaslundBh commented
@BHoMBot check copyright-compliance

2022-01-11 14:56 UTC, IsakNaslundBh commented
@BHoMBot check copyright-compliance
@BHoMBot check required

2022-01-11 15:42 UTC, merged