Fix Bug when Creating Bars in ETABS21
BHoM/ETABS_Toolkit pull request #483
Opened 2024-10-28 18:43 UTC by GCRA101

### Issues addressed by this PR

 Closes #

 

 ### Test files

 ### Changelog

 ### Additional comments

2024-10-31 17:02 UTC, peterjamesnugent requested changes
If you're adding an alternate configuration, you will need to add it to the installer:
https://github.com/BHoM/BHoM_Installer/blob/develop/IncludedRepos/altConfigs.txt

2024-10-31 17:02 UTC, peterjamesnugent commented on Etabs_Adapter/Etabs_Adapter.csproj
> +  </PropertyGroup>
Does all this need to be added if it was not there previously?

2024-10-31 17:02 UTC, peterjamesnugent commented on Etabs_Adapter/CRUD/Create/Bar.cs
> +#endif
Does this actually work in practice? You can simplify the if statement, but just checking `#if Debug21' - VS has quite a good UI feature that highlights the code that is active dependent on the build configuration.

2024-11-07 14:13 UTC, peterjamesnugent commented
@GCRA101 as discussed to add altconfigs to installer and update preprocessor directives to `#if Debug21 || Release 21` etc.

2024-11-25 16:10 UTC, Chrisshort92 commented
@BHoMBot check installer

2024-11-25 16:31 UTC, Chrisshort92 commented
@BHoMBot Check Installer

2025-01-16 09:09 UTC, IsakNaslundBh requested changes
I had a look into this and although a separate build configuration could help resolve this problem, it is something I think we want to stray away from as much as possible. Ideally there should not be any separate build configurations at all except debug and release.

Reason it has been done before was out of neccesity though to different names of the ETABS api dlls, and change on method interfaces that required these directives to go everywhere, but as this is not the case now, I think we rather solve this runtime than compile time.

Instead of adding this additional configuration, and all compiler directives that comes with it, I think we can simply get out the version of the currently runnign ETABS model. Had a first check, and 

```
                string modelVersion = "";
                double doubleVer = 0;
                m_app.SapModel.GetVersion(ref modelVersion, ref doubleVer);

```

Is giving back the version of the currently running model. We can extract this in the constructor of the ETABS adapter and store it, and then simply have a normal if statement at the position in the code that is causing the problem (think it was insertion points for Bars if I am not mistaken).

![image](https://github.com/user-attachments/assets/faa28ce6-7cf5-44f2-a1d7-39aa9ffeaba2)

![image](https://github.com/user-attachments/assets/2e34d64b-bbb7-4f4b-8693-3453ffbe70ea)


Also, not sure exactly what has happened to this branch, but it is currently looking like it is containing commits from more or less everything that has gone in to develop since the past 3 months which makes it impossible to review unfortunately, so would suggest starting fresh from a new branch from develop and get the code fix added to that branch, with the suggested chage from here as well, basically, start from scratch with a new PR and branch, lift over the parts you need, then delete this PR and branch.

Happy with a quick call about this if it helps.

2025-01-20 15:17 UTC, closed without merging